name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'b472291f295551b7127359ea38fdd2ca092f6f1b'

      - name: Prepare CommonLibF4
        shell: bash
        run: cp cmake/CommonLibF4.cmake.txt extern/CommonLibF4/CMakeLists.txt

      - name: Configure
        run: cmake -S . --preset=default

      - name: Build
        run: cmake --build build --config Release

      - name: Upload AAAFrameGeneration
        uses: actions/upload-artifact@v4
        with:
          name: AAAFrameGeneration
          path: build/plugins/FrameGeneration/Release/AAAFrameGeneration.dll

      - name: Upload Upscaling
        uses: actions/upload-artifact@v4
        with:
          name: Upscaling
          path: build/plugins/Upscaling/Release/Upscaling.dll
